set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY XPM_FIFO XPM_COMP_DECL} [current_project]

set files {
 ./hardware/deps/cva6/include/riscv_pkg.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dm_pkg.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_pkg.sv \
 ./hardware/deps/cva6/include/ariane_pkg.sv \
 ./hardware/deps/common_cells/src/cf_math_pkg.sv \
 ./hardware/include/rvv_pkg.sv \
 ./hardware/deps/axi/src/axi_pkg.sv \
 ./hardware/include/ara_pkg.sv \
 ./hardware/src/vlsu/addrgen.sv \
 ./hardware/deps/cva6/include/ariane_axi_pkg.sv \
 ./hardware/deps/common_cells/include/common_cells/registers.svh \
 ./hardware/src/ara_dispatcher.sv \
 ./hardware/src/ara_sequencer.sv \
 ./hardware/deps/axi/include/axi/typedef.svh \
 ./hardware/deps/axi/include/axi/assign.svh \
 ./hardware/deps/axi/src/axi_cut.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv \
 ./hardware/deps/common_cells/src/counter.sv \
 ./hardware/deps/common_cells/src/delta_counter.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv \
 ./hardware/deps/common_cells/src/fall_through_register.sv \
 ./hardware/deps/common_cells/src/deprecated/fifo_v2.sv \
 ./hardware/deps/common_cells/src/fifo_v3.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_cast_multi.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_classifier.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_divsqrt_multi.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_fma.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_fma_multi.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_noncomp.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_opgroup_block.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_opgroup_fmt_slice.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_opgroup_multifmt_slice.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_rounding.sv \
 ./hardware/deps/cva6/src/fpu/src/fpnew_top.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv \
 ./hardware/include/ara/ara.svh \
 ./hardware/src/lane/lane.sv \
 ./hardware/src/lane/lane_sequencer.sv \
 ./hardware/deps/common_cells/src/lzc.sv \
 ./hardware/src/masku/masku.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv \
 ./hardware/src/lane/operand_queue.sv \
 ./hardware/src/lane/operand_queues_stage.sv \
 ./hardware/src/lane/operand_requester.sv \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv \
 ./hardware/deps/common_cells/src/rr_arb_tree.sv \
 ./hardware/deps/cva6/src/serdiv.sv \
 ./hardware/src/lane/simd_alu.sv \
 ./hardware/src/lane/simd_div.sv \
 ./hardware/src/lane/simd_mul.sv \
 ./hardware/src/sldu/sldu.sv \
 ./hardware/deps/common_cells/src/spill_register.sv \
 ./hardware/deps/common_cells/src/spill_register_flushable.sv \
 ./hardware/deps/common_cells/src/stream_demux.sv \
 ./hardware/deps/common_cells/src/stream_register.sv \
 ./hardware/deps/common_cells/src/stream_xbar.sv \
 ./hardware/deps/tech_cells_generic/src/fpga/tc_sram_xilinx.sv \
 ./hardware/src/lane/valu.sv \
 ./hardware/src/lane/vector_fus_stage.sv \
 ./hardware/src/lane/vector_regfile.sv \
 ./hardware/src/vlsu/vldu.sv \
 ./hardware/src/vlsu/vlsu.sv \
 ./hardware/src/lane/vmfpu.sv \
 ./hardware/src/vlsu/vstu.sv \
 ./hardware/src/ara.sv \
 ./hardware/deps/common_cells/src/addr_decode.sv \
 ./hardware/src/ara_system.sv \
 ./hardware/deps/axi/src/axi_atop_filter.sv \
 ./hardware/deps/axi/src/axi_burst_splitter.sv \
 ./hardware/deps/axi/src/axi_demux.sv \
 ./hardware/deps/axi/src/axi_dw_converter.sv \
 ./hardware/deps/axi/src/axi_dw_downsizer.sv \
 ./hardware/deps/axi/src/axi_dw_upsizer.sv \
 ./hardware/deps/axi/src/axi_err_slv.sv \
 ./hardware/deps/axi/src/axi_id_prepend.sv \
 ./hardware/src/axi_inval_filter.sv \
 ./hardware/deps/axi/src/axi_lite_regs.sv \
 ./hardware/deps/axi/src/axi_mux.sv \
 ./hardware/deps/axi/src/axi_to_axi_lite.sv \
 ./hardware/src/axi_to_mem.sv \
 ./hardware/deps/axi/src/axi_xbar.sv \
 ./hardware/src/ctrl_registers.sv \
 ./hardware/deps/common_cells/src/id_queue.sv \
 ./hardware/deps/common_cells/src/onehot_to_bin.sv \
 ./hardware/deps/common_cells/src/stream_fifo.sv \
 ./hardware/deps/common_cells/src/stream_fork.sv \
 ./hardware/deps/common_cells/src/stream_fork_dynamic.sv \
 ./hardware/deps/common_cells/src/stream_join.sv \
 ./hardware/deps/common_cells/src/stream_mux.sv \
 ./hardware/deps/common_cells/src/stream_to_mem.sv \
 ./hardware/src/ara_soc.sv \
 ./hardware/src/cva6_accel_first_pass_decoder.sv \
 ./hardware/deps/axi/src/axi_intf.sv \
 ./hardware/deps/axi/src/axi_sim_mem.sv \
 ./hardware/deps/axi/src/axi_cdc.sv \
 ./hardware/deps/axi/src/axi_cdc_src.sv \
 ./hardware/deps/axi/src/axi_modify_address.sv \
 ./hardware/deps/axi/src/axi_delayer.sv \
 ./hardware/deps/axi/src/axi_join.sv \
 ./hardware/deps/axi/src/axi_lite_mailbox.sv \
 ./hardware/deps/axi/src/axi_lite_to_apb.sv \
 ./hardware/deps/axi/src/axi_lite_join.sv \
 ./hardware/deps/axi/src/axi_lite_to_axi.sv \
 ./hardware/deps/axi/src/axi_lite_mux.sv \
 ./hardware/deps/axi/src/axi_lite_demux.sv \
 ./hardware/deps/axi/src/axi_isolate.sv \
 ./hardware/deps/axi/src/axi_test.sv \
 ./hardware/deps/axi/src/axi_lite_xbar.sv \
 ./hardware/deps/axi/src/axi_cdc_dst.sv \
 ./hardware/deps/axi/src/axi_multicut.sv \
 ./hardware/deps/axi/src/axi_serializer.sv \
 ./hardware/deps/common_cells/src/stream_omega_net.sv \
 ./hardware/deps/common_cells/src/binary_to_gray.sv \
 ./hardware/deps/common_cells/src/cdc_fifo_gray.sv \
 ./hardware/deps/common_cells/src/cdc_2phase.sv \
 ./hardware/deps/common_cells/src/cdc_fifo_2phase.sv \
 ./hardware/deps/common_cells/src/plru_tree.sv \
 ./hardware/deps/common_cells/src/rstgen.sv \
 ./hardware/deps/common_cells/src/ecc_decode.sv \
 ./hardware/deps/common_cells/src/stream_delay.sv \
 ./hardware/deps/common_cells/src/unread.sv \
 ./hardware/deps/common_cells/src/rstgen_bypass.sv \
 ./hardware/deps/common_cells/src/isochronous_spill_register.sv \
 ./hardware/deps/common_cells/src/lfsr_8bit.sv \
 ./hardware/deps/common_cells/src/exp_backoff.sv \
 ./hardware/deps/common_cells/src/serial_deglitch.sv \
 ./hardware/deps/common_cells/src/lfsr.sv \
 ./hardware/deps/common_cells/src/stream_arbiter.sv \
 ./hardware/deps/common_cells/src/sub_per_hash.sv \
 ./hardware/deps/common_cells/src/popcount.sv \
 ./hardware/deps/common_cells/src/sync_wedge.sv \
 ./hardware/deps/common_cells/src/ecc_pkg.sv \
 ./hardware/deps/common_cells/src/edge_propagator_tx.sv \
 ./hardware/deps/common_cells/src/stream_filter.sv \
 ./hardware/deps/common_cells/src/stream_arbiter_flushable.sv \
 ./hardware/deps/common_cells/src/lfsr_16bit.sv \
 ./hardware/deps/common_cells/src/sync.sv \
 ./hardware/deps/common_cells/src/edge_propagator.sv \
 ./hardware/deps/common_cells/src/gray_to_binary.sv \
 ./hardware/deps/common_cells/src/clk_div.sv \
 ./hardware/deps/common_cells/src/mv_filter.sv \
 ./hardware/deps/common_cells/src/shift_reg.sv \
 ./hardware/deps/common_cells/src/cb_filter.sv \
 ./hardware/deps/common_cells/src/stream_intf.sv \
 ./hardware/deps/common_cells/src/ecc_encode.sv \
 ./hardware/deps/common_cells/src/cb_filter_pkg.sv \
 ./hardware/deps/common_cells/src/max_counter.sv \
 ./hardware/deps/common_cells/src/edge_propagator_rx.sv \
 ./hardware/deps/common_cells/src/edge_detect.sv \
 ./hardware/deps/cva6/include/axi_intf.sv \
 ./hardware/deps/cva6/include/traced_instr_pkg.sv \
 ./hardware/deps/cva6/include/instr_tracer_pkg.sv \
 ./hardware/deps/cva6/include/std_cache_pkg.sv \
 ./hardware/deps/cva6/include/wt_cache_pkg.sv \
 ./hardware/deps/common_cells/src/deprecated/generic_fifo_adv.sv \
 ./hardware/deps/common_cells/src/deprecated/generic_fifo.sv \
 ./hardware/deps/common_cells/src/deprecated/rrarbiter.sv \
 ./hardware/deps/common_cells/src/deprecated/sram.sv \
 ./hardware/deps/common_cells/src/deprecated/pulp_sync_wedge.sv \
 ./hardware/deps/common_cells/src/deprecated/pulp_sync.sv \
 ./hardware/deps/common_cells/src/deprecated/find_first_one.sv \
 ./hardware/deps/common_cells/src/deprecated/fifo_v1.sv \
 ./hardware/deps/common_cells/src/deprecated/generic_LFSR_8bit.sv \
 ./hardware/deps/common_cells/src/deprecated/clock_divider.sv \
 ./hardware/deps/common_cells/src/deprecated/clock_divider_counter.sv \
 ./hardware/deps/common_cells/src/deprecated/prioarbiter.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dm_sba.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dmi_cdc.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dm_mem.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dm_top.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dm_csrs.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dmi_jtag.sv \
 ./hardware/deps/cva6/src/riscv-dbg/src/dmi_jtag_tap.sv \
 ./hardware/deps/tech_cells_generic/src/tc_pwr.sv \
 ./hardware/deps/common_cells/include/common_cells/assertions.svh \
 ./hardware/deps/cva6/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv \
 ./hardware/deps/cva6/src/load_unit.sv \
 ./hardware/deps/cva6/src/controller.sv \
 ./hardware/deps/cva6/src/instr_realign.sv \
 ./hardware/deps/cva6/src/load_store_unit.sv \
 ./hardware/deps/cva6/src/alu.sv \
 ./hardware/deps/cva6/src/ptw.sv \
 ./hardware/deps/cva6/src/compressed_decoder.sv \
 ./hardware/deps/cva6/src/axi_adapter.sv \
 ./hardware/deps/cva6/src/store_unit.sv \
 ./hardware/deps/cva6/src/decoder.sv \
 ./hardware/deps/cva6/src/mult.sv \
 ./hardware/deps/cva6/src/branch_unit.sv \
 ./hardware/deps/cva6/src/csr_buffer.sv \
 ./hardware/deps/cva6/src/axi_shim.sv \
 ./hardware/deps/cva6/src/re_name.sv \
 ./hardware/deps/cva6/src/tlb.sv \
 ./hardware/deps/cva6/src/multiplier.sv \
 ./hardware/deps/cva6/src/fpu_wrap.sv \
 ./hardware/deps/cva6/src/acc_dispatcher.sv \
 ./hardware/deps/cva6/src/ariane.sv \
 ./hardware/deps/cva6/src/scoreboard.sv \
 ./hardware/deps/cva6/src/issue_read_operands.sv \
 ./hardware/deps/cva6/src/ariane_regfile_ff.sv \
 ./hardware/deps/cva6/src/dromajo_ram.sv \
 ./hardware/deps/cva6/src/mmu.sv \
 ./hardware/deps/cva6/src/csr_regfile.sv \
 ./hardware/deps/cva6/src/id_stage.sv \
 ./hardware/deps/cva6/src/perf_counters.sv \
 ./hardware/deps/cva6/src/ariane_regfile.sv \
 ./hardware/deps/cva6/src/store_buffer.sv \
 ./hardware/deps/cva6/src/ex_stage.sv \
 ./hardware/deps/cva6/src/issue_stage.sv \
 ./hardware/deps/cva6/src/commit_stage.sv \
 ./hardware/deps/cva6/src/amo_buffer.sv \
}


set files { \
 ../hardware/deps/common_cells/src/cf_math_pkg.sv \
 ../hardware/deps/cva6/include/riscv_pkg.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dm_pkg.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_pkg.sv \
 ../hardware/deps/cva6/include/ariane_pkg.sv \
 ../hardware/include/rvv_pkg.sv \
 ../hardware/deps/axi/src/axi_pkg.sv \
 ../hardware/include/ara_pkg.sv \
 ../hardware/src/vlsu/addrgen.sv \
 ../hardware/deps/common_cells/include/common_cells/registers.svh \
 ../hardware/src/ara_dispatcher.sv \
 ../hardware/src/ara_sequencer.sv \
 ../hardware/deps/axi/include/axi/typedef.svh \
 ../hardware/deps/axi/include/axi/assign.svh \
 ../hardware/deps/axi/src/axi_cut.sv \
 ../hardware/deps/common_cells/src/counter.sv \
 ../hardware/deps/common_cells/src/delta_counter.sv \
 ../hardware/deps/common_cells/src/fall_through_register.sv \
 ../hardware/deps/common_cells/src/deprecated/fifo_v2.sv \
 ../hardware/deps/common_cells/src/fifo_v3.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_cast_multi.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_classifier.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_divsqrt_multi.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_fma.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_fma_multi.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_noncomp.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_opgroup_block.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_opgroup_fmt_slice.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_opgroup_multifmt_slice.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_rounding.sv \
 ../hardware/deps/cva6/src/fpu/src/fpnew_top.sv \
 ../hardware/include/ara/ara.svh \
 ../hardware/src/lane/lane.sv \
 ../hardware/src/lane/lane_sequencer.sv \
 ../hardware/deps/common_cells/src/lzc.sv \
 ../hardware/src/masku/masku.sv \
 ../hardware/src/lane/operand_queue.sv \
 ../hardware/src/lane/operand_queues_stage.sv \
 ../hardware/src/lane/operand_requester.sv \
 ../hardware/deps/common_cells/src/rr_arb_tree.sv \
 ../hardware/src/lane/simd_alu.sv \
 ../hardware/src/lane/simd_div.sv \
 ../hardware/src/lane/simd_mul.sv \
 ../hardware/src/sldu/sldu.sv \
 ../hardware/deps/common_cells/src/spill_register.sv \
 ../hardware/deps/common_cells/src/spill_register_flushable.sv \
 ../hardware/deps/common_cells/src/stream_demux.sv \
 ../hardware/deps/common_cells/src/stream_register.sv \
 ../hardware/deps/common_cells/src/stream_xbar.sv \
 ../hardware/deps/tech_cells_generic/src/fpga/tc_sram_xilinx.sv \
 ../hardware/src/lane/valu.sv \
 ../hardware/src/lane/vector_fus_stage.sv \
 ../hardware/src/lane/vector_regfile.sv \
 ../hardware/src/vlsu/vldu.sv \
 ../hardware/src/vlsu/vlsu.sv \
 ../hardware/src/lane/vmfpu.sv \
 ../hardware/src/vlsu/vstu.sv \
 ../hardware/src/ara.sv \
 ../hardware/deps/common_cells/src/addr_decode.sv \
 ../hardware/src/ara_system.sv \
 ../hardware/deps/axi/src/axi_atop_filter.sv \
 ../hardware/deps/axi/src/axi_burst_splitter.sv \
 ../hardware/deps/axi/src/axi_demux.sv \
 ../hardware/deps/axi/src/axi_dw_converter.sv \
 ../hardware/deps/axi/src/axi_dw_downsizer.sv \
 ../hardware/deps/axi/src/axi_dw_upsizer.sv \
 ../hardware/deps/axi/src/axi_err_slv.sv \
 ../hardware/deps/axi/src/axi_id_prepend.sv \
 ../hardware/src/axi_inval_filter.sv \
 ../hardware/deps/axi/src/axi_lite_regs.sv \
 ../hardware/deps/axi/src/axi_mux.sv \
 ../hardware/deps/axi/src/axi_to_axi_lite.sv \
 ../hardware/src/axi_to_mem.sv \
 ../hardware/deps/axi/src/axi_xbar.sv \
 ../hardware/src/ctrl_registers.sv \
 ../hardware/deps/common_cells/src/id_queue.sv \
 ../hardware/deps/common_cells/src/onehot_to_bin.sv \
 ../hardware/deps/common_cells/src/stream_fifo.sv \
 ../hardware/deps/common_cells/src/stream_fork.sv \
 ../hardware/deps/common_cells/src/stream_fork_dynamic.sv \
 ../hardware/deps/common_cells/src/stream_join.sv \
 ../hardware/deps/common_cells/src/stream_mux.sv \
 ../hardware/deps/common_cells/src/stream_to_mem.sv \
 ../hardware/src/ara_soc.sv \
 ../hardware/src/cva6_accel_first_pass_decoder.sv \
 ../hardware/deps/axi/src/axi_intf.sv \
 ../hardware/deps/axi/src/axi_sim_mem.sv \
 ../hardware/deps/axi/src/axi_cdc.sv \
 ../hardware/deps/axi/src/axi_cdc_src.sv \
 ../hardware/deps/axi/src/axi_modify_address.sv \
 ../hardware/deps/axi/src/axi_delayer.sv \
 ../hardware/deps/axi/src/axi_join.sv \
 ../hardware/deps/axi/src/axi_lite_mailbox.sv \
 ../hardware/deps/axi/src/axi_lite_to_apb.sv \
 ../hardware/deps/axi/src/axi_lite_join.sv \
 ../hardware/deps/axi/src/axi_lite_to_axi.sv \
 ../hardware/deps/axi/src/axi_lite_mux.sv \
 ../hardware/deps/axi/src/axi_lite_demux.sv \
 ../hardware/deps/axi/src/axi_isolate.sv \
 ../hardware/deps/axi/src/axi_test.sv \
 ../hardware/deps/axi/src/axi_lite_xbar.sv \
 ../hardware/deps/axi/src/axi_cdc_dst.sv \
 ../hardware/deps/axi/src/axi_multicut.sv \
 ../hardware/deps/axi/src/axi_serializer.sv \
 ../hardware/deps/common_cells/src/stream_omega_net.sv \
 ../hardware/deps/common_cells/src/binary_to_gray.sv \
 ../hardware/deps/common_cells/src/cdc_fifo_gray.sv \
 ../hardware/deps/common_cells/src/cdc_2phase.sv \
 ../hardware/deps/common_cells/src/cdc_fifo_2phase.sv \
 ../hardware/deps/common_cells/src/plru_tree.sv \
 ../hardware/deps/common_cells/src/rstgen.sv \
 ../hardware/deps/common_cells/src/ecc_decode.sv \
 ../hardware/deps/common_cells/src/stream_delay.sv \
 ../hardware/deps/common_cells/src/unread.sv \
 ../hardware/deps/common_cells/src/rstgen_bypass.sv \
 ../hardware/deps/common_cells/src/isochronous_spill_register.sv \
 ../hardware/deps/common_cells/src/lfsr_8bit.sv \
 ../hardware/deps/common_cells/src/exp_backoff.sv \
 ../hardware/deps/common_cells/src/serial_deglitch.sv \
 ../hardware/deps/common_cells/src/lfsr.sv \
 ../hardware/deps/common_cells/src/stream_arbiter.sv \
 ../hardware/deps/common_cells/src/sub_per_hash.sv \
 ../hardware/deps/common_cells/src/popcount.sv \
 ../hardware/deps/common_cells/src/sync_wedge.sv \
 ../hardware/deps/common_cells/src/ecc_pkg.sv \
 ../hardware/deps/common_cells/src/edge_propagator_tx.sv \
 ../hardware/deps/common_cells/src/stream_filter.sv \
 ../hardware/deps/common_cells/src/stream_arbiter_flushable.sv \
 ../hardware/deps/common_cells/src/lfsr_16bit.sv \
 ../hardware/deps/common_cells/src/sync.sv \
 ../hardware/deps/common_cells/src/edge_propagator.sv \
 ../hardware/deps/common_cells/src/gray_to_binary.sv \
 ../hardware/deps/common_cells/src/clk_div.sv \
 ../hardware/deps/common_cells/src/mv_filter.sv \
 ../hardware/deps/common_cells/src/shift_reg.sv \
 ../hardware/deps/common_cells/src/cb_filter.sv \
 ../hardware/deps/common_cells/src/stream_intf.sv \
 ../hardware/deps/common_cells/src/ecc_encode.sv \
 ../hardware/deps/common_cells/src/cb_filter_pkg.sv \
 ../hardware/deps/common_cells/src/max_counter.sv \
 ../hardware/deps/common_cells/src/edge_propagator_rx.sv \
 ../hardware/deps/common_cells/src/edge_detect.sv \
 ../hardware/deps/cva6/include/ariane_axi_pkg.sv \
 ../hardware/deps/cva6/include/axi_intf.sv \
 ../hardware/deps/cva6/include/traced_instr_pkg.sv \
 ../hardware/deps/cva6/include/instr_tracer_pkg.sv \
 ../hardware/deps/cva6/include/std_cache_pkg.sv \
 ../hardware/deps/cva6/include/wt_cache_pkg.sv \
 ../hardware/deps/common_cells/src/deprecated/generic_fifo_adv.sv \
 ../hardware/deps/common_cells/src/deprecated/generic_fifo.sv \
 ../hardware/deps/common_cells/src/deprecated/rrarbiter.sv \
 ../hardware/deps/common_cells/src/deprecated/sram.sv \
 ../hardware/deps/common_cells/src/deprecated/pulp_sync_wedge.sv \
 ../hardware/deps/common_cells/src/deprecated/pulp_sync.sv \
 ../hardware/deps/common_cells/src/deprecated/find_first_one.sv \
 ../hardware/deps/common_cells/src/deprecated/fifo_v1.sv \
 ../hardware/deps/common_cells/src/deprecated/generic_LFSR_8bit.sv \
 ../hardware/deps/common_cells/src/deprecated/clock_divider.sv \
 ../hardware/deps/common_cells/src/deprecated/clock_divider_counter.sv \
 ../hardware/deps/common_cells/src/deprecated/prioarbiter.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dm_sba.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dmi_cdc.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dm_mem.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dm_top.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dm_csrs.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dmi_jtag.sv \
 ../hardware/deps/cva6/src/riscv-dbg/src/dmi_jtag_tap.sv \
 ../hardware/deps/tech_cells_generic/src/tc_pwr.sv \
 ../hardware/deps/common_cells/include/common_cells/assertions.svh \
}

add_files -norecurse $files
